name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make build dir
      run: mkdir build
    - name: cmake 
      working-directory: build
      run: cmake ..
    - name: make
      working-directory: build
      run: make
  
